name: weather_calendar
description: Weather Calendar app (Glassmorphism) using Open-Meteo.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  dio: ^5.7.0
  table_calendar: ^3.1.2
  fl_chart: ^0.69.0
  geolocator: ^13.0.2
  intl: ^0.20.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^6.2.1
  collection: ^1.18.0
  path_provider: ^2.1.1
  flutter_slidable: ^3.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/weather_icons/
    - assets/images/
    - assets/icons/
    - assets/database/
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather/Merriweather-Regular.ttf
        - asset: assets/fonts/Merriweather/Merriweather-Bold.ttf
          weight: 700
        - asset: assets/fonts/Merriweather/Merriweather-Light.ttf
          weight: 300
        - asset: assets/fonts/Merriweather/Merriweather-Italic.ttf
          style: italic
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico/Pacifico-Regular.ttf
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat/Caveat-Regular.ttf
        - asset: assets/fonts/Caveat/Caveat-Medium.ttf
          weight: 500